#!/bin/bash
set -euo pipefail

if [ -z "${AWS_LAMBDA_RUNTIME_API:-}" ]; then
  echo "Not running inside AWS Lambda. Exiting..."
  exit 0
fi

# Update our virus definitions
./usr/bin/freshclam

exec python3 /var/task/app.py
